Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false