Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false